"""Initial gateway migration

Revision ID: 9cd3740305ac
Revises: 20260215_customer_chat_tables
Create Date: 2026-02-15 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cd3740305ac'
down_revision = '20260215_customer_chat_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.create_table('mission_outbox',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_outbox_event_type'), 'mission_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_mission_outbox_status'), 'mission_outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index(op.f('ix_mission_outbox_status'), table_name='mission_outbox')
    op.drop_index(op.f('ix_mission_outbox_event_type'), table_name='mission_outbox')
    op.drop_table('mission_outbox')
    # ### end Alembic commands ###
