#!/usr/bin/env bash
# =============================================================================
# compose_env_from_secrets.sh — auto-generate .env for the Docker full stack
# =============================================================================
# Bridges secrets into `docker compose up` the same "100% automatic" way
# supervisor.sh:_inject_env_secrets feeds the uvicorn path. Resolution order per
# key (first non-empty wins):
#
#   1. Process environment  (Codespaces Secrets / devcontainer remoteEnv / shell)
#   2. .devcontainer/secrets.env   (git-ignored local fallback)
#
# Writes the repo-root .env that `docker compose` reads. Never prints secret
# values. Idempotent: safe to re-run. See CLAUDE.md §6.144 (D-172).
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
SECRETS_FILE="$REPO_ROOT/.devcontainer/secrets.env"

# ── Load .devcontainer/secrets.env as a fallback layer (process env wins) ─────
# Read each KEY=VALUE and export ONLY when the key is unset/empty in the process
# env — mirrors supervisor.sh so Codespaces Secrets always take priority.
if [[ -f "$SECRETS_FILE" ]]; then
  echo "[compose-env] loading fallback from .devcontainer/secrets.env"
  while IFS= read -r line; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// }" ]] && continue
    key="${line%%=*}"
    val="${line#*=}"
    [[ -z "$key" ]] && continue
    if [[ -z "${!key:-}" ]]; then
      export "$key=$val"
    fi
  done <"$SECRETS_FILE"
fi

# ── Tavily sanitizer: accept the MCP-URL form, emit the bare tvly-... key ──────
sanitize_tavily() {
  local raw="${1:-}"
  if [[ "$raw" == *"tavilyApiKey="* ]]; then
    raw="${raw##*tavilyApiKey=}"   # strip everything up to and incl. the param
    raw="${raw%%&*}"               # strip any trailing &params
  fi
  printf '%s' "$raw"
}

OPENROUTER_API_KEY_V="${OPENROUTER_API_KEY:-}"
TAVILY_API_KEY_V="$(sanitize_tavily "${TAVILY_API_KEY:-}")"
SECRET_KEY_V="${SECRET_KEY:-}"
POSTGRES_USER_V="${POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD_V="${POSTGRES_PASSWORD:-password}"
GRAFANA_ADMIN_PASSWORD_V="${GRAFANA_ADMIN_PASSWORD:-admin}"

# A stable, self-generated SECRET_KEY if none was provided (dev/self-contained).
if [[ -z "$SECRET_KEY_V" ]]; then
  SECRET_KEY_V="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fi

# ── Write .env (compose reads it automatically) ───────────────────────────────
{
  echo "# Auto-generated by scripts/compose_env_from_secrets.sh — do not commit."
  echo "# Self-contained Docker full stack (local Postgres/Redis). See .env.example."
  echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY_V}"
  echo "TAVILY_API_KEY=${TAVILY_API_KEY_V}"
  echo "SECRET_KEY=${SECRET_KEY_V}"
  echo "POSTGRES_USER=${POSTGRES_USER_V}"
  echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD_V}"
  echo "GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD_V}"
} >"$ENV_FILE"
chmod 600 "$ENV_FILE"

# ── Report presence (never values) ────────────────────────────────────────────
present() { [[ -n "$1" ]] && echo "SET" || echo "MISSING"; }
echo "[compose-env] wrote $ENV_FILE"
echo "[compose-env]   OPENROUTER_API_KEY   : $(present "$OPENROUTER_API_KEY_V")"
echo "[compose-env]   TAVILY_API_KEY       : $(present "$TAVILY_API_KEY_V")"
echo "[compose-env]   SECRET_KEY           : SET (provided or generated)"
echo "[compose-env]   POSTGRES_USER/PASS   : SET (defaults if unset)"
if [[ -z "$OPENROUTER_API_KEY_V" ]]; then
  echo "[compose-env] WARNING: OPENROUTER_API_KEY is empty — LLM answers will be mock/degraded." >&2
fi
