"""Initial schema

Revision ID: 001_initial_schema
Revises:
Create Date: 2023-10-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.create_table('missions',
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PLANNING', 'PLANNED', 'RUNNING', 'ADAPTING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', 'CANCELED', name='missionstatus'), nullable=True),
    sa.Column('active_plan_id', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('adaptive_cycles', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_idempotency_key'), 'missions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_missions_initiator_id'), 'missions', ['initiator_id'], unique=False)

    op.create_table('mission_plans',
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('planner_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALID', 'INVALID', 'SELECTED', 'ABANDONED', name='planstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_plans_mission_id'), 'mission_plans', ['mission_id'], unique=False)

    op.create_table('tasks',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_args_json', sa.Text(), nullable=True),
    sa.Column('depends_on_json', sa.Text(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('result_meta_json', sa.Text(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('task_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRY', 'SKIPPED', name='taskstatus'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('criticality', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['mission_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_mission_id'), 'tasks', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tasks_plan_id'), 'tasks', ['plan_id'], unique=False)

    op.create_table('mission_events',
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STATUS_CHANGE', 'ARCHITECTURE_CLASSIFIED', 'PLAN_SELECTED', 'EXECUTION_STARTED', 'TASK_STARTED', 'TASK_COMPLETED', 'TASK_FAILED', 'REPLAN_TRIGGERED', 'REPLAN_APPLIED', 'RISK_SUMMARY', 'MISSION_COMPLETED', 'MISSION_FAILED', 'FINALIZED', name='missioneventtype'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_events_mission_id'), 'mission_events', ['mission_id'], unique=False)

    op.create_table('mission_outbox',
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_outbox_event_type'), 'mission_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_mission_outbox_mission_id'), 'mission_outbox', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_outbox_status'), 'mission_outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index(op.f('ix_mission_outbox_status'), table_name='mission_outbox')
    op.drop_index(op.f('ix_mission_outbox_mission_id'), table_name='mission_outbox')
    op.drop_index(op.f('ix_mission_outbox_event_type'), table_name='mission_outbox')
    op.drop_table('mission_outbox')
    op.drop_index(op.f('ix_mission_events_mission_id'), table_name='mission_events')
    op.drop_table('mission_events')
    op.drop_index(op.f('ix_tasks_plan_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_mission_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_mission_plans_mission_id'), table_name='mission_plans')
    op.drop_table('mission_plans')
    op.drop_index(op.f('ix_missions_initiator_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_idempotency_key'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
